import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { Card } from "@/components/ui/Card";

export const metadata = {
  title: "Privacy Policy — Zero",
};

export default function PrivacyPage() {
  return (
    <AppShell>
      <header className="mb-5">
        <Link href="/settings" className="text-sm font-medium text-primary">
          ← Back
        </Link>
        <h1 className="mt-2 text-2xl font-semibold tracking-tight text-foreground">Privacy Policy</h1>
        <p className="mt-1 text-sm text-muted-foreground">Last updated August 2026</p>
      </header>

      <div className="flex flex-col gap-4 text-sm leading-relaxed text-foreground">
        <Card>
          <p className="font-semibold text-primary">The short version</p>
          <p className="mt-1 text-muted-foreground">
            Zero doesn&apos;t have a server for your financial data. Everything you enter — income, expenses,
            debts, balances — is stored only in your browser or on your device. We never receive it, see it, or
            have any way to access it. There is nothing for us to sell, leak, or hand over, because we never have
            it in the first place.
          </p>
        </Card>

        <Card>
          <p className="font-semibold">What Zero stores, and where</p>
          <p className="mt-1 text-muted-foreground">
            All financial information you enter — income and expenses logged on the Wallet tab, debts, balances,
            interest rates, and your progress/achievements — is saved locally using your browser&apos;s or
            device&apos;s on-device storage (IndexedDB). It is not transmitted to Zero, its developer, or any third
            party. If you use the installed app on iOS or Android, the same rule applies: your data lives on that
            device, inside that app&apos;s private storage.
          </p>
        </Card>

        <Card>
          <p className="font-semibold">What we don&apos;t do</p>
          <ul className="mt-1 list-inside list-disc space-y-1 text-muted-foreground">
            <li>No account or sign-up, so there&apos;s no email or password of yours for us to store.</li>
            <li>No analytics or tracking of how you use the app.</li>
            <li>No advertising, and no sharing or selling of data — we don&apos;t have any to share.</li>
            <li>No bank account connections. You enter your numbers manually.</li>
            <li>No cookies used for tracking.</li>
          </ul>
        </Card>

        <Card>
          <p className="font-semibold">Notifications</p>
          <p className="mt-1 text-muted-foreground">
            If you turn on notifications, your browser or device handles showing them locally, based on the same
            on-device data described above. No reminder content is sent through, or generated by, a server.
          </p>
        </Card>

        <Card>
          <p className="font-semibold">Deleting your data</p>
          <p className="mt-1 text-muted-foreground">
            Go to Settings → Reset all data to permanently erase everything Zero has stored, at any time. Because
            nothing exists outside your device, this is complete — there is no copy anywhere else to also delete.
            Uninstalling the app, or clearing your browser&apos;s site data for Zero, has the same effect.
          </p>
        </Card>

        <Card>
          <p className="font-semibold">Children&apos;s privacy</p>
          <p className="mt-1 text-muted-foreground">
            Zero is not directed at children under 13 and does not knowingly collect information from them — in
            practice, since the app collects nothing at all, there is no data of any kind for anyone to submit.
          </p>
        </Card>

        <Card>
          <p className="font-semibold">Not financial advice</p>
          <p className="mt-1 text-muted-foreground">
            Zero is a planning and education tool. It is not a bank, lender, or registered financial advisor, and
            nothing in the app is personalized financial, tax, or legal advice. Calculations are estimates based
            on the numbers you enter.
          </p>
        </Card>

        <Card>
          <p className="font-semibold">Changes to this policy</p>
          <p className="mt-1 text-muted-foreground">
            If Zero ever adds a feature that changes what data leaves your device (for example, an optional cloud
            backup or a real AI service), this page will be updated first, and that change will be clearly opt-in.
          </p>
        </Card>

        <Card>
          <p className="font-semibold">Contact</p>
          <p className="mt-1 text-muted-foreground">
            Questions about this policy can be sent to the developer via the contact listed on the app&apos;s store
            page.
          </p>
        </Card>
      </div>
    </AppShell>
  );
}
